-- =====================================================
-- Yeungnam University Notice Bot V2 - Schema
-- =====================================================

-- Enable pgvector for embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Notices Table
CREATE TABLE IF NOT EXISTS notices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    site_key TEXT NOT NULL,          -- e.g., 'yu_news', 'cse'
    article_id TEXT NOT NULL,        -- Unique ID from source
    title TEXT NOT NULL,
    content TEXT,                    -- Body text
    content_hash TEXT,               -- Hash(Title + Body + Attachments)
    url TEXT,
    category TEXT,                   -- AI Classified Category
    summary TEXT,                    -- AI Summary
    target_grades INTEGER[],         -- [1, 2, 3, 4]
    target_dept TEXT,                -- e.g. "Computer Science"
    start_date DATE,
    end_date DATE,
    
    -- Metadata
    published_at TIMESTAMPTZ,        -- Original post date
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Notification Status
    message_ids JSONB DEFAULT '{}'::jsonb, -- {'telegram': 123, 'discord': 'id'}
    
    -- AI Embeddings
    embedding VECTOR(768),
    image_url TEXT,
    
    UNIQUE(site_key, article_id)
);

-- 2. Attachments Table
CREATE TABLE IF NOT EXISTS attachments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    notice_id UUID REFERENCES notices(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    url TEXT NOT NULL
);

-- 3. Token Usage Tracking
CREATE TABLE IF NOT EXISTS token_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Menus Table (Dormitory Meal Plans)
CREATE TABLE IF NOT EXISTS menus (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    notice_id UUID REFERENCES notices(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    raw_text TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_notices_site_key ON notices(site_key);
CREATE INDEX IF NOT EXISTS idx_notices_created_at ON notices(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_menus_created_at ON menus(created_at DESC);
