-- =====================================================
-- Yeungnam University Notice Bot V2 - Database Schema
-- Latest Version: v6
-- =====================================================
-- 
-- This is the COMPLETE schema for NEW installations.
-- For existing databases, see migrations/ folder.
--
-- Changelog:
--   v6: Added ai_models table for AI rate limit tracking
-- =====================================================

-- Enable pgvector for embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- =====================================================
-- 1. Notices Table (Core)
-- =====================================================
CREATE TABLE IF NOT EXISTS notices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    
    -- Identity
    site_key TEXT NOT NULL,              -- e.g., 'yu_news', 'cse'
    article_id TEXT NOT NULL,            -- Unique ID from source
    
    -- Content
    title TEXT NOT NULL,
    content TEXT,                        -- Body text
    content_hash TEXT,                   -- Hash(Title + Body + Attachments + Images)
    url TEXT,
    attachment_text TEXT,                -- Extracted text from HWP/PDF
    
    -- AI Classification
    category TEXT,                       -- AI classified category
    summary TEXT,                        -- AI summary
    tags TEXT[],                         -- AI-selected tags (Discord forum)
    
    -- AI Metadata
    target_grades INTEGER[],             -- [1, 2, 3, 4]
    target_dept TEXT,                    -- e.g. "Computer Science"
    eligibility TEXT[],                  -- Eligibility criteria
    deadline DATE,                       -- Application deadline
    start_date DATE,                     -- Event/program start
    end_date DATE,                       -- Event/program end
    
    -- Metadata
    published_at TIMESTAMPTZ,            -- Original post date
    author TEXT,                         -- Notice author/department
    image_urls TEXT[] DEFAULT '{}',      -- Multiple images support
    extra_info JSONB DEFAULT '{}'::jsonb,-- Extra metadata (OCR, raw data)
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Notification Tracking
    message_ids JSONB DEFAULT '{}'::jsonb,   -- {'telegram': 123, 'discord': 'id'}
    discord_thread_id TEXT,                  -- Discord forum thread ID
    
    -- AI Embeddings
    embedding VECTOR(768),
    
    UNIQUE(site_key, article_id)
);

-- =====================================================
-- 2. Attachments Table
-- =====================================================
CREATE TABLE IF NOT EXISTS attachments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    notice_id UUID REFERENCES notices(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    file_size BIGINT,
    etag TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 3. Token Usage Tracking
-- =====================================================
CREATE TABLE IF NOT EXISTS token_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 4. AI Models (Rate Limit Tracking)
-- =====================================================
CREATE TABLE IF NOT EXISTS ai_models (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    model_name TEXT NOT NULL UNIQUE,
    daily_limit INTEGER DEFAULT 1500,
    current_usage INTEGER DEFAULT 0,
    reset_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 5. Menus Table (Dormitory Meal Plans)
-- =====================================================
CREATE TABLE IF NOT EXISTS menus (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    notice_id UUID REFERENCES notices(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    raw_text TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- Indexes
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_notices_site_key ON notices(site_key);
CREATE INDEX IF NOT EXISTS idx_notices_created_at ON notices(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notices_content_hash ON notices(content_hash);
CREATE INDEX IF NOT EXISTS idx_notices_tags ON notices USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_attachments_notice_id ON attachments(notice_id);
CREATE INDEX IF NOT EXISTS idx_menus_created_at ON menus(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_token_usage_timestamp ON token_usage(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_ai_models_model_name ON ai_models(model_name);

-- =====================================================
-- Comments
-- =====================================================
COMMENT ON TABLE notices IS 'University notices collected from various sources';
COMMENT ON TABLE attachments IS 'File attachments associated with notices';
COMMENT ON TABLE token_usage IS 'AI token usage tracking for cost monitoring';
COMMENT ON TABLE ai_models IS 'AI model rate limit tracking';
COMMENT ON TABLE menus IS 'Dormitory meal plans extracted from notices';

COMMENT ON COLUMN notices.site_key IS 'Source identifier (e.g., yu_news, cse_notice)';
COMMENT ON COLUMN notices.content_hash IS 'SHA256 hash for change detection';
COMMENT ON COLUMN notices.image_urls IS 'Array of image URLs found in notice content';
COMMENT ON COLUMN notices.tags IS 'AI-selected tags for Discord forum categorization';
COMMENT ON COLUMN notices.discord_thread_id IS 'Discord forum thread ID for update replies';
COMMENT ON COLUMN notices.attachment_text IS 'Extracted text from HWP/PDF files for AI analysis';
COMMENT ON COLUMN notices.extra_info IS 'Extra metadata (OCR results, raw API data)';
